export interface JobDetail {
  title: string;
  dept: string;
  deptKey: string;
  location: string;
  type: string;
  compensation: string;
  openings: number;
  image: string;
  description: string;
  responsibilities: string[];
  requirements: string[];
  bonusSkills: string[];
  benefits: string[];
  skills: string[];
  customQuestions: string[];
}

export const JOB_DETAILS: JobDetail[] = [
  {
    title: "AI Web Developer Intern(+Marketing)",
    dept: "Web Development",
    deptKey: "web",
    location: "Remote",
    type: "Full Time",
    compensation: "Unpaid",
    openings: 18,
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=600&q=80",
    description:
      "Join LocalSM as an AI Web Developer and contribute to building the next generation of our local commerce platform. You'll leverage AI tools to design, build, and iterate on real product features that directly impact thousands of users in Jabalpur and beyond. This is a remote, hands-on role ideal for self-starters who want to learn fast and ship real work.",
    responsibilities: [
      "Develop and maintain front-end and back-end features using modern web technologies.",
      "Integrate AI tools and APIs (e.g., OpenAI, Gemini) into the platform.",
      "Collaborate with the product and design team on new feature specs.",
      "Write clean, well-documented code that can be reviewed and maintained.",
      "Participate in weekly team check-ins and async standups.",
      "Research and propose AI-driven improvements to existing workflows.",
    ],
    requirements: [
      "Basic to intermediate knowledge of HTML, CSS, JavaScript, or React.",
      "Curiosity about AI tools and how they can be applied to real products.",
      "Ability to work independently and manage your own time remotely.",
      "Clear communication in English (spoken and written).",
      "Willingness to commit at least 2–4 hours daily.",
    ],
    bonusSkills: [
      "Experience with Next.js, Tailwind CSS, or Node.js.",
      "Prior use of AI tools like ChatGPT, GitHub Copilot, or similar.",
      "Any open-source contributions or personal projects.",
    ],
    benefits: [
      "Certificate of completion issued upon successful internship.",
      "Real project experience on a live platform.",
      "Letter of recommendation for strong performers.",
      "Potential conversion to a paid role or equity consideration.",
      "Flexible hours — work from anywhere.",
    ],
    skills: ["AI"],
    customQuestions: [
      "Why do you want to work with LocalSM?",
      "What skills make you suitable for this role?",
      "Share links to any previous work, portfolio, or social pages.",
      "How many hours daily can you dedicate?",
      "Are you available for meetings or field visits if required?",
      "Are you comfortable working in a startup environment?",
    ],
  },
  {
    title: "UI/UX Designer",
    dept: "Web Development",
    deptKey: "web",
    location: "Remote",
    type: "Full Time",
    compensation: "Unpaid",
    openings: 2,
    image: "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=600&q=80",
    description:
      "We're looking for a creative and detail-oriented UI/UX Designer to join the LocalSM team remotely. You'll own the visual design and user experience of our marketplace — from wireframes to polished UI — ensuring that every screen is intuitive, beautiful, and on-brand. This is a rare opportunity to shape a product from an early stage.",
    responsibilities: [
      "Design wireframes, mockups, and interactive prototypes for new features.",
      "Conduct user research and translate findings into design improvements.",
      "Maintain and evolve the LocalSM design system and component library.",
      "Collaborate with developers to ensure designs are implemented accurately.",
      "Iterate on feedback from users and stakeholders quickly.",
      "Create assets for social media, marketing, and product use.",
    ],
    requirements: [
      "Proficiency in Figma or Adobe XD for design and prototyping.",
      "Strong eye for layout, typography, color, and visual hierarchy.",
      "Understanding of mobile-first and responsive design principles.",
      "Ability to present and justify design decisions clearly.",
      "Portfolio showcasing at least 2–3 UI/UX projects.",
    ],
    bonusSkills: [
      "Motion design or micro-animation experience.",
      "Familiarity with HTML/CSS to better collaborate with developers.",
      "Experience designing for e-commerce or marketplace apps.",
    ],
    benefits: [
      "Certificate of completion issued upon successful internship.",
      "Real product design experience on a live platform.",
      "Letter of recommendation for strong performers.",
      "Portfolio-worthy projects you can show publicly.",
      "Flexible hours — work from anywhere.",
    ],
    skills: ["Designing"],
    customQuestions: [
      "Why do you want to work with LocalSM?",
      "Share links to any previous work, portfolio, or social pages.",
      "What skills make you suitable for this role?",
      "How many hours daily can you dedicate?",
      "Are you available for meetings or field visits if required?",
      "Are you comfortable working in a startup environment?",
    ],
  },
  {
    title: "AI Graphics Designer",
    dept: "Graphics Design",
    deptKey: "graphics",
    location: "Remote",
    type: "Full Time",
    compensation: "Unpaid",
    openings: 13,
    image: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=600&q=80",
    description:
      "LocalSM is looking for an AI Graphics Designer who combines creative design skills with the power of AI-driven tools. You'll create stunning visuals for the platform, marketing campaigns, and social media — using tools like Midjourney, DALL·E, Adobe Firefly, or Canva AI to accelerate quality output. This is a remote role with real creative ownership.",
    responsibilities: [
      "Create high-quality graphics for social media, ads, banners, and in-app use.",
      "Use AI tools (Midjourney, Firefly, DALL·E, etc.) to ideate and produce visuals quickly.",
      "Maintain brand consistency across all visual outputs.",
      "Collaborate with the marketing and product teams on campaign briefs.",
      "Deliver print-ready and web-ready assets on time.",
    ],
    requirements: [
      "Proficiency in graphic design tools (Canva, Photoshop, Illustrator, or similar).",
      "Active experience using AI image generation tools.",
      "Strong sense of color, composition, and brand identity.",
      "Ability to handle multiple design requests and meet deadlines.",
    ],
    bonusSkills: [
      "Video editing or motion graphics experience.",
      "Experience creating visuals for Indian local-commerce brands.",
      "Knowledge of print production and file formats.",
    ],
    benefits: [
      "Certificate of completion issued upon successful internship.",
      "Creative freedom on real campaigns.",
      "Portfolio-worthy work published on live channels.",
      "Letter of recommendation for strong performers.",
    ],
    skills: ["AI", "Workflow"],
    customQuestions: [
      "Why do you want to work with LocalSM?",
      "Share links to any previous work, portfolio, or social pages.",
      "What skills make you suitable for this role?",
      "How many hours daily can you dedicate?",
    ],
  },
  {
    title: "Data Analyst Intern(+Marketing)",
    dept: "Product Management",
    deptKey: "product",
    location: "Remote",
    type: "Full Time",
    compensation: "Unpaid",
    openings: 2,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80",
    description:
      "As a Data Analyst Intern at LocalSM, you'll work closely with the product and marketing teams to turn raw data into clear, actionable insights. You'll help us understand how users interact with our marketplace, what drives conversions, and where we have room to grow — all using real platform data.",
    responsibilities: [
      "Collect, clean, and analyze data from platform analytics and marketing tools.",
      "Build dashboards and reports to track key product and marketing metrics.",
      "Identify trends and anomalies and surface insights to the team.",
      "Support A/B testing efforts and interpret results.",
      "Assist in social media performance tracking and audience analysis.",
      "Document findings clearly for both technical and non-technical stakeholders.",
    ],
    requirements: [
      "Basic understanding of data analysis and spreadsheet tools (Excel, Google Sheets).",
      "Comfort working with data sets and identifying patterns.",
      "Strong written communication skills for presenting findings.",
      "Willingness to learn analytics platforms (Google Analytics, Mixpanel, etc.).",
    ],
    bonusSkills: [
      "Experience with SQL or Python for data querying.",
      "Familiarity with visualization tools like Tableau or Looker Studio.",
      "Prior experience managing or tracking social media metrics.",
    ],
    benefits: [
      "Certificate of completion issued upon successful internship.",
      "Hands-on experience with real business data.",
      "Letter of recommendation for strong performers.",
      "Flexible hours — work from anywhere.",
    ],
    skills: ["AI", "Data", "Product", "Management"],
    customQuestions: [
      "What skills make you suitable for this role?",
      "Why do you want to work with LocalSM?",
      "Share links to any previous work, portfolio, or social pages.",
      "How many hours daily can you dedicate?",
      "Are you comfortable working in a startup environment?",
      "Are you available for meetings or field visits if required?",
      "Have you handled social media pages before? If yes, which platforms?",
    ],
  },
  {
    title: "Product Management Intern",
    dept: "Product Management",
    deptKey: "product",
    location: "Remote",
    type: "Full Time",
    compensation: "Unpaid",
    openings: 13,
    image: "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=600&q=80",
    description:
      "We're looking for a curious, structured thinker to join LocalSM as a Product Management Intern. You'll work directly with the founding team to help prioritize features, write product specs, track execution, and ensure that what gets built actually solves real user problems. This is a high-ownership role for someone who wants to understand how products are built end-to-end.",
    responsibilities: [
      "Assist in writing product requirement documents (PRDs) and user stories.",
      "Conduct user research and synthesize findings into product insights.",
      "Track feature development progress and flag blockers.",
      "Coordinate between design, engineering, and marketing teams.",
      "Analyze product metrics and contribute to growth experiments.",
      "Participate in sprint planning and retrospective sessions.",
    ],
    requirements: [
      "Strong logical thinking and structured communication.",
      "Ability to create clear documentation and presentations.",
      "Eagerness to learn product development processes hands-on.",
      "Good understanding of user-centric design principles.",
    ],
    bonusSkills: [
      "Prior PM internship or product-building experience.",
      "Familiarity with tools like Notion, Jira, Figma, or Linear.",
      "Basic understanding of analytics or data-driven decision making.",
    ],
    benefits: [
      "Certificate of completion issued upon successful internship.",
      "Direct mentorship from the founder on product strategy.",
      "Real ownership over features shipped to production.",
      "Letter of recommendation for strong performers.",
      "Flexible hours — work from anywhere.",
    ],
    skills: ["Product", "Management"],
    customQuestions: [
      "Why do you want to work with LocalSM?",
      "What skills make you suitable for this role?",
      "Share links to any previous work, portfolio, or social pages.",
      "How many hours daily can you dedicate?",
      "Are you comfortable working in a startup environment?",
      "Are you available for meetings or field visits if required?",
    ],
  },
  {
    title: "Quality Assurance Intern",
    dept: "QA",
    deptKey: "qa",
    location: "Remote",
    type: "Full Time",
    compensation: "Unpaid",
    openings: 14,
    image: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=600&q=80",
    description:
      "As a QA Intern at LocalSM, you'll be the last line of defense before features go live. You'll test new builds, document bugs in detail, verify fixes, and help maintain a high standard of quality across the platform. This is a great role for someone methodical, detail-obsessed, and interested in how software products are built and shipped.",
    responsibilities: [
      "Test new features and existing functionality across web and mobile surfaces.",
      "Document bugs clearly with steps to reproduce, screenshots, and severity tags.",
      "Collaborate with developers to verify bug fixes before release.",
      "Maintain test case documentation and track coverage.",
      "Perform regression testing on each new build.",
      "Suggest improvements to the QA process as the team grows.",
    ],
    requirements: [
      "Strong attention to detail and methodical thinking.",
      "Ability to think like a user and break things intentionally.",
      "Clear written communication for bug reports.",
      "Basic understanding of how web or mobile applications work.",
    ],
    bonusSkills: [
      "Experience with tools like JIRA, Notion, or TestRail.",
      "Basic knowledge of automation testing (Selenium, Cypress, etc.).",
      "Familiarity with browser developer tools.",
    ],
    benefits: [
      "Certificate of completion issued upon successful internship.",
      "Experience working on a live production platform.",
      "Letter of recommendation for strong performers.",
      "Flexible hours — work from anywhere.",
    ],
    skills: ["AI", "Data", "Testing", "Bug Detection"],
    customQuestions: [
      "Why do you want to work with LocalSM?",
      "What skills make you suitable for this role?",
      "Share links to any previous work, portfolio, or social pages.",
      "How many hours daily can you dedicate?",
      "Are you comfortable working in a startup environment?",
      "Are you available for meetings or field visits if required?",
    ],
  },
  {
    title: "Junior Social Media Management Intern",
    dept: "Marketing",
    deptKey: "marketing",
    location: "Remote",
    type: "Full Time",
    compensation: "Unpaid",
    openings: 10,
    image: "https://images.unsplash.com/photo-1611926653458-09294b3142bf?w=600&q=80",
    description:
      "LocalSM is growing its social media presence and we need passionate creators to help us get there. As a Social Media Management Intern, you'll manage day-to-day content across our platforms, engage with our audience, and help us grow a loyal community of local shoppers and sellers in Jabalpur.",
    responsibilities: [
      "Create and schedule posts across Instagram, Facebook, and other platforms.",
      "Engage with comments, DMs, and community interactions daily.",
      "Assist in planning monthly content calendars aligned with campaigns.",
      "Monitor social analytics and report on reach, engagement, and growth.",
      "Collaborate with the graphics team to brief and source visuals.",
      "Research trends relevant to local commerce and Jabalpur audiences.",
    ],
    requirements: [
      "Active presence and understanding of Instagram and Facebook.",
      "Good writing skills in Hindi and/or English.",
      "Creativity and ability to generate ideas for engaging posts.",
      "Consistency and reliability in daily task execution.",
    ],
    bonusSkills: [
      "Experience managing a brand or personal page with an audience.",
      "Short-form video content creation (Reels, YouTube Shorts).",
      "Canva or basic design skills for social graphics.",
    ],
    benefits: [
      "Certificate of completion issued upon successful internship.",
      "Real social media management experience on a growing brand.",
      "Letter of recommendation for strong performers.",
      "Flexible hours — work from anywhere.",
    ],
    skills: ["Marketing", "Management"],
    customQuestions: [
      "Why do you want to work with LocalSM?",
      "What skills make you suitable for this role?",
      "Share links to any previous work, portfolio, or social pages.",
      "How many hours daily can you dedicate?",
      "Are you comfortable working in a startup environment?",
    ],
  },
  {
    title: "On-Site Marketing Intern",
    dept: "Marketing",
    deptKey: "marketing",
    location: "Jabalpur",
    type: "Full Time",
    compensation: "Unpaid + Incentives",
    openings: 41,
    image: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=600&q=80",
    description:
      "This is LocalSM's most impactful ground-level role. As an On-Site Marketing Intern, you'll be out in Jabalpur's markets, mohallas, and business districts — talking to local vendors, handing out materials, building awareness, and helping bring more sellers onto our platform. If you're energetic, social, and love the idea of building something in your own city, this role is for you.",
    responsibilities: [
      "Visit local vendors, shops, and markets across Jabalpur to pitch LocalSM.",
      "Distribute marketing materials (flyers, pamphlets, stickers) in target areas.",
      "Onboard interested sellers by collecting basic information and guiding sign-up.",
      "Report daily activity logs and leads to the marketing team.",
      "Attend weekly check-ins with the team to share on-ground feedback.",
      "Represent the LocalSM brand professionally in all interactions.",
    ],
    requirements: [
      "Based in Jabalpur and available for field visits most weekdays.",
      "Strong communication skills in Hindi (and basic English).",
      "Confident, friendly, and persuasive in person.",
      "Self-motivated — able to work independently without micromanagement.",
    ],
    bonusSkills: [
      "Prior experience in sales, outreach, or field marketing.",
      "Existing network of local business owners in Jabalpur.",
      "Basic smartphone skills for submitting reports and photos.",
    ],
    benefits: [
      "Certificate of completion issued upon successful internship.",
      "Performance-based incentives for every seller successfully onboarded.",
      "Letter of recommendation for strong performers.",
      "Opportunity to grow into a paid field marketing role.",
    ],
    skills: ["Communication", "Hindi", "English", "Social Skills"],
    customQuestions: [
      "Why do you want to work with LocalSM?",
      "What skills make you suitable for this role?",
      "Share links to any previous work, portfolio, or social pages.",
      "How many hours daily can you dedicate?",
      "Are you comfortable working in a startup environment?",
      "Are you available for meetings or field visits if required?",
    ],
  },
  {
    title: "Cybersecurity Intern",
    dept: "Cybersecurity",
    deptKey: "cybersecurity",
    location: "Remote",
    type: "Full Time",
    compensation: "Unpaid",
    openings: 12,
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600&q=80",
    description:
      "LocalSM is building a trusted commerce platform and security is at the heart of it. As a Cybersecurity Intern, you'll help identify vulnerabilities, assist in security audits, and support the team in maintaining a safe environment for users and vendors. This role is ideal for someone studying or self-learning cybersecurity who wants real-world exposure.",
    responsibilities: [
      "Assist in identifying and documenting security vulnerabilities in the platform.",
      "Conduct basic penetration testing under senior guidance.",
      "Review code and infrastructure for common security weaknesses.",
      "Help implement security best practices across the codebase.",
      "Research emerging threats relevant to e-commerce platforms.",
      "Document findings in clear, actionable reports for the engineering team.",
    ],
    requirements: [
      "Basic understanding of web security concepts (OWASP Top 10, XSS, SQL injection, etc.).",
      "Familiarity with network fundamentals and how web applications work.",
      "Eagerness to learn and apply security practices in a real product.",
      "Ability to document and communicate findings clearly.",
    ],
    bonusSkills: [
      "Experience with tools like Burp Suite, Nmap, Wireshark, or Metasploit.",
      "Any certifications: CEH, CompTIA Security+, or similar.",
      "Prior CTF (Capture The Flag) competition experience.",
    ],
    benefits: [
      "Certificate of completion issued upon successful internship.",
      "Real-world security audit experience on a live platform.",
      "Letter of recommendation for strong performers.",
      "Flexible hours — work from anywhere.",
    ],
    skills: ["Vulnerability Detection"],
    customQuestions: [
      "Why do you want to work with LocalSM?",
      "What skills make you suitable for this role?",
      "Share links to any previous work, portfolio, or social pages.",
      "How many hours daily can you dedicate?",
      "Are you comfortable working in a startup environment?",
      "Are you available for meetings or field visits if required?",
    ],
  },
  {
    title: "Senior Manager",
    dept: "Management",
    deptKey: "management",
    location: "Jabalpur (On-Site)",
    type: "Full Time",
    compensation: "Unpaid",
    openings: 1,
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&q=80",
    description:
      "LocalSM is looking for a Senior Manager to join our founding team and help bring structure, strategy, and execution to our growing operations. This is a senior, on-site role in Jabalpur for someone who is deeply motivated to build a local-first tech company from the ground up. You'll work directly with the founder across operations, team management, partnerships, and growth.",
    responsibilities: [
      "Oversee day-to-day team operations and intern management.",
      "Set weekly goals, track progress, and hold team members accountable.",
      "Work with the founder to execute business development and partner outreach.",
      "Manage communications with vendors, merchants, and external partners.",
      "Identify inefficiencies and propose process improvements.",
      "Represent LocalSM in official meetings and at local events.",
    ],
    requirements: [
      "Strong leadership, organizational, and communication skills.",
      "Ability to manage people and drive results without close supervision.",
      "Based in or willing to relocate to Jabalpur.",
      "Comfortable working in an early-stage, resource-constrained startup.",
      "High ownership mindset — treats the company's success as personal success.",
    ],
    bonusSkills: [
      "Prior experience in operations, management, or team leadership.",
      "Background in business development or local commerce.",
      "Fluency in Hindi and English.",
    ],
    benefits: [
      "Certificate of completion and formal role title issued.",
      "Equity or revenue-share consideration for exceptional performance.",
      "Letter of recommendation for strong performers.",
      "Co-founder consideration for the right candidate.",
    ],
    skills: ["Data", "Management", "Communication", "Social Skills"],
    customQuestions: [
      "Why do you want to work with LocalSM?",
      "What skills make you suitable for this role?",
      "Share links to any previous work, portfolio, or social pages.",
      "How many hours daily can you dedicate?",
      "Are you comfortable working in a startup environment?",
      "Are you available for meetings or field visits if required?",
    ],
  },
];
